version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build
          command: yarn install
      - run:
          name: Lint code
          command: yarn lint
      # - run:
      #     name: Functional tests
      #     command: yarn test
  # deploy:
  #   docker:
  #     - image: buildpack-deps:trusty
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy Master to Heroku
  #         command: |
  #           git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  release:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build
          command: yarn install
      - run:
          name: Setup custom environment variables
          command: |
            echo 'export $GITHUB_TOKEN' >> $BASH_ENV

      - run: git config --global user.email $GITHUB_EMAIL
      - run: git config --global user.name $GITHUB_USER
      - run: git config --global push.default matching

      - add_ssh_keys:
          fingerprints:
            - 'de:d7:0a:53:2c:d4:24:9a:17:97:b3:af:be:34:9e:8d'
      - run:
          name: Release
          command: yarn release

workflows:
  version: 2
  build-deploy:
    jobs:
      # - build
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
      - release:
          # requires:
          #   - deploy
          filters:
            branches:
              only: master
