name: Install and build project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set Node.js 18.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command

      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: build # will run `yarn build` command
